name: Update Plugins List

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *' # Runs daily at midnight UTC


jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - name:   Checkout Repository
        uses: actions/checkout@v3

      - name: Download plugins file
        run: |
          curl -D - -o scripts/chatgpt_plugins.json -c cookies.txt -b cookies.txt -H "Authorization: Bearer ${{ secrets.AUTH_TOKEN }}" -H "Content-Type: application/json" -L ${{ vars.PLUGINS_FILE_URL }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update ChatGPT plugins file
          title: Update ChatGPT plugins file
          body: |
            This is an automated pull request to update the ChatGPT plugins file.
          branch: update-plugins-file
          branch-suffix: timestamp
          base: master
          draft: false
          signoff: false
          delete-branch: true
          add-paths: scripts/chatgpt_plugins.json

      
